"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
exports.__esModule = true;
exports.Inventory = void 0;
var flatbuffers = require("flatbuffers");
var collectables_in_level_1 = require("../../penguin-game/serialization/collectables-in-level");
var death_count_in_level_1 = require("../../penguin-game/serialization/death-count-in-level");
var Inventory = /** @class */ (function () {
    function Inventory() {
        this.bb = null;
        this.bb_pos = 0;
    }
    Inventory.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    Inventory.getRootAsInventory = function (bb, obj) {
        return (obj || new Inventory()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    Inventory.getSizePrefixedRootAsInventory = function (bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new Inventory()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    Inventory.prototype.collectables = function (index, obj) {
        var offset = this.bb.__offset(this.bb_pos, 4);
        return offset ? (obj || new collectables_in_level_1.CollectablesInLevel()).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
    };
    Inventory.prototype.collectablesLength = function () {
        var offset = this.bb.__offset(this.bb_pos, 4);
        return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
    };
    Inventory.prototype.deathCounts = function (index, obj) {
        var offset = this.bb.__offset(this.bb_pos, 6);
        return offset ? (obj || new death_count_in_level_1.DeathCountInLevel()).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
    };
    Inventory.prototype.deathCountsLength = function () {
        var offset = this.bb.__offset(this.bb_pos, 6);
        return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
    };
    Inventory.startInventory = function (builder) {
        builder.startObject(2);
    };
    Inventory.addCollectables = function (builder, collectablesOffset) {
        builder.addFieldOffset(0, collectablesOffset, 0);
    };
    Inventory.createCollectablesVector = function (builder, data) {
        builder.startVector(4, data.length, 4);
        for (var i = data.length - 1; i >= 0; i--) {
            builder.addOffset(data[i]);
        }
        return builder.endVector();
    };
    Inventory.startCollectablesVector = function (builder, numElems) {
        builder.startVector(4, numElems, 4);
    };
    Inventory.addDeathCounts = function (builder, deathCountsOffset) {
        builder.addFieldOffset(1, deathCountsOffset, 0);
    };
    Inventory.createDeathCountsVector = function (builder, data) {
        builder.startVector(4, data.length, 4);
        for (var i = data.length - 1; i >= 0; i--) {
            builder.addOffset(data[i]);
        }
        return builder.endVector();
    };
    Inventory.startDeathCountsVector = function (builder, numElems) {
        builder.startVector(4, numElems, 4);
    };
    Inventory.endInventory = function (builder) {
        var offset = builder.endObject();
        return offset;
    };
    Inventory.createInventory = function (builder, collectablesOffset, deathCountsOffset) {
        Inventory.startInventory(builder);
        Inventory.addCollectables(builder, collectablesOffset);
        Inventory.addDeathCounts(builder, deathCountsOffset);
        return Inventory.endInventory(builder);
    };
    return Inventory;
}());
exports.Inventory = Inventory;
