"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
exports.__esModule = true;
exports.CollectablesOfType = void 0;
var flatbuffers = require("flatbuffers");
var collectable_1 = require("../../penguin-game/serialization/collectable");
var CollectablesOfType = /** @class */ (function () {
    function CollectablesOfType() {
        this.bb = null;
        this.bb_pos = 0;
    }
    CollectablesOfType.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    CollectablesOfType.getRootAsCollectablesOfType = function (bb, obj) {
        return (obj || new CollectablesOfType()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    CollectablesOfType.getSizePrefixedRootAsCollectablesOfType = function (bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new CollectablesOfType()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    CollectablesOfType.prototype.collectableGuid = function (optionalEncoding) {
        var offset = this.bb.__offset(this.bb_pos, 4);
        return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
    };
    CollectablesOfType.prototype.collectables = function (index, obj) {
        var offset = this.bb.__offset(this.bb_pos, 6);
        return offset ? (obj || new collectable_1.Collectable()).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
    };
    CollectablesOfType.prototype.collectablesLength = function () {
        var offset = this.bb.__offset(this.bb_pos, 6);
        return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
    };
    CollectablesOfType.startCollectablesOfType = function (builder) {
        builder.startObject(2);
    };
    CollectablesOfType.addCollectableGuid = function (builder, collectableGuidOffset) {
        builder.addFieldOffset(0, collectableGuidOffset, 0);
    };
    CollectablesOfType.addCollectables = function (builder, collectablesOffset) {
        builder.addFieldOffset(1, collectablesOffset, 0);
    };
    CollectablesOfType.createCollectablesVector = function (builder, data) {
        builder.startVector(4, data.length, 4);
        for (var i = data.length - 1; i >= 0; i--) {
            builder.addOffset(data[i]);
        }
        return builder.endVector();
    };
    CollectablesOfType.startCollectablesVector = function (builder, numElems) {
        builder.startVector(4, numElems, 4);
    };
    CollectablesOfType.endCollectablesOfType = function (builder) {
        var offset = builder.endObject();
        builder.requiredField(offset, 4); // collectable_guid
        return offset;
    };
    CollectablesOfType.createCollectablesOfType = function (builder, collectableGuidOffset, collectablesOffset) {
        CollectablesOfType.startCollectablesOfType(builder);
        CollectablesOfType.addCollectableGuid(builder, collectableGuidOffset);
        CollectablesOfType.addCollectables(builder, collectablesOffset);
        return CollectablesOfType.endCollectablesOfType(builder);
    };
    return CollectablesOfType;
}());
exports.CollectablesOfType = CollectablesOfType;
