// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { Inventory } from '../../penguin-game/serialization/inventory';


export class PenguinSaveData {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):PenguinSaveData {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPenguinSaveData(bb:flatbuffers.ByteBuffer, obj?:PenguinSaveData):PenguinSaveData {
  return (obj || new PenguinSaveData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPenguinSaveData(bb:flatbuffers.ByteBuffer, obj?:PenguinSaveData):PenguinSaveData {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new PenguinSaveData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

inventory(obj?:Inventory):Inventory|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new Inventory()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startPenguinSaveData(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addInventory(builder:flatbuffers.Builder, inventoryOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, inventoryOffset, 0);
}

static endPenguinSaveData(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishPenguinSaveDataBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedPenguinSaveDataBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static createPenguinSaveData(builder:flatbuffers.Builder, inventoryOffset:flatbuffers.Offset):flatbuffers.Offset {
  PenguinSaveData.startPenguinSaveData(builder);
  PenguinSaveData.addInventory(builder, inventoryOffset);
  return PenguinSaveData.endPenguinSaveData(builder);
}
}
